server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      auto.register.schemas: true

logging:
  level:
    ru.yandex.practicum.kafka.telemetry.collector: DEBUG